name: Bzlmod Archive

on:
  workflow_call: {}

jobs:
  # A release archive is required for bzlmod
  # See: https://blog.bazel.build/2023/02/15/github-archive-checksum.html
  upload-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git archive -o "${{ format('{0}-{1}.tar.gz', github.event.repository.name, github.event.release.tag_name) }}" HEAD
      - run: gh release upload ${{ github.event.release.tag_name }} *.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Notify Bazel Registry
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ECSACT_BAZEL_REGISTRY_TOKEN }}
          repository: ecsact-dev/bazel_registry
          event-type: notify-bzlmod-archive
          client-payload: >-
            {
              "repo": "${{ github.event.repository.name }}", 
              "tag_name": "${{ github.event.release.tag_name }}",
              "archive": "${{ format('https://github.com/ecsact-dev/{0}/releases/download/{1}/{0}-{1}.tar.gz', github.event.repository.name, github.event.release.tag_name) }}"
            }
